#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("watchman.Resource", IsApplication=true)]

namespace watchman
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FacebookMonoDroid.Resource.String.library_name = global::watchman.Resource.String.library_name;
			global::Gcm.Client.Resource.String.library_name = global::watchman.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int alarm = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int banner = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int discon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int emer = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int monoandroidsplash = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ok = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int warn = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060005
			public const int btnDial = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int btnState = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int btnStatus = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout2 = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int linearLayout3 = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int app_name = 2130968580;
			
			// aapt resource value: 0x7f04000b
			public const int event_type_alarm_code = 2130968587;
			
			// aapt resource value: 0x7f040012
			public const int event_type_alarm_desc = 2130968594;
			
			// aapt resource value: 0x7f04000e
			public const int event_type_cancel_code = 2130968590;
			
			// aapt resource value: 0x7f040015
			public const int event_type_cancel_desc = 2130968597;
			
			// aapt resource value: 0x7f04000c
			public const int event_type_ok_code = 2130968588;
			
			// aapt resource value: 0x7f040014
			public const int event_type_ok_desc = 2130968596;
			
			// aapt resource value: 0x7f04000d
			public const int event_type_warn_code = 2130968589;
			
			// aapt resource value: 0x7f040013
			public const int event_type_warning_desc = 2130968595;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040011
			public const int reason_fall_code = 2130968593;
			
			// aapt resource value: 0x7f040018
			public const int reason_fall_desc = 2130968600;
			
			// aapt resource value: 0x7f04000f
			public const int reason_gas_code = 2130968591;
			
			// aapt resource value: 0x7f040016
			public const int reason_gas_desc = 2130968598;
			
			// aapt resource value: 0x7f040010
			public const int reason_panic_code = 2130968592;
			
			// aapt resource value: 0x7f040017
			public const int reason_panic_desc = 2130968599;
			
			// aapt resource value: 0x7f040003
			public const int ring_111 = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int status = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int status_alarm = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int status_disconnected = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int status_ok = 2130968581;
			
			// aapt resource value: 0x7f04000a
			public const int status_ok_cancel = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int status_panic = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int status_warning = 2130968584;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
