//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRChatApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public string id { get; set; }
        public System.DateTimeOffset C__createdAt { get; set; }
        public Nullable<System.DateTimeOffset> C__updatedAt { get; set; }
        public byte[] C__version { get; set; }
        public string care_receiver { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string home_phone { get; set; }
        public string office_phone { get; set; }
        public string relationship { get; set; }
        public Nullable<double> primary_contact { get; set; }
        public string email_id { get; set; }
    }
}
